import { PostMortemResult } from "../types";

function invisibleVetoHolder(result: PostMortemResult): string {
  const stakeholders = result.stakeholders ?? [];
  const veto =
    stakeholders.find((s) => /hidden detractor|absent decision maker/i.test(s.persona_type ?? s.stance ?? "")) ??
    stakeholders.find((s) => /technical_veto|economic_buyer/i.test(s.authority_level ?? ""));
  if (!veto) return "Not identified — review People Map";
  return `${veto.name}${veto.role ? ` (${veto.role})` : ""} — ${veto.persona_type ?? veto.stance}`;
}

function coreBlocker(result: PostMortemResult): string {
  const eq = result.equilibrium_analysis;
  const init = result.force_initialization;
  const force = (result.causal_forces ?? []).find(
    (f) => f.type === "Constraint" || f.type === "Structural"
  );
  return (
    eq?.equilibrium_breaker?.trim() ||
    init?.classification_rationale?.trim() ||
    force?.factor?.trim() ||
    init?.summary?.trim() ||
    "See full autopsy for blocker detail"
  );
}

function nextActionDate(result: PostMortemResult): string {
  const immediate = result.rescue_triage_plan?.immediate_0_30_days?.[0];
  if (!immediate) return "Within 7 days";
  const dateMatch = immediate.match(/\b(20\d{2}-\d{2}-\d{2}|\d{1,2}\/\d{1,2}\/\d{2,4})\b/);
  return dateMatch ? dateMatch[1] : "Within 30 days";
}

function thirtyDayPriority(result: PostMortemResult): string {
  if (result.immediate_remediation?.length) {
    return result.immediate_remediation.slice(0, 2).map((item, i) => `${i + 1}. ${item}`).join("\n");
  }
  const items = result.rescue_triage_plan?.immediate_0_30_days ?? [];
  if (!items.length) return result.crm_intelligence?.recommended_next_action ?? "Re-engage champion";
  return items.slice(0, 2).map((item, i) => `${i + 1}. ${item}`).join("\n");
}

/** Compressed markdown for HubSpot / Salesforce paste in under two seconds. */
export function formatCompressedCrmNotes(result: PostMortemResult): string {
  const client = result.client_name?.trim() || "Unknown account";
  const status = result.deal_classification?.status ?? result.deal_status ?? "STALLED";
  const rootIssue =
    result.live_deal_triage?.root_issue?.trim() ||
    result.executive_summary?.trim() ||
    result.diagnosis?.trim() ||
    "Stalled sequence — see blocker";
  const blocker =
    result.live_deal_triage?.core_blocker?.trim() || coreBlocker(result);
  const veto = invisibleVetoHolder(result);
  const nextDate = nextActionDate(result);
  const priority = thirtyDayPriority(result);
  const dri = result.proprietary_indices?.deal_risk_index;

  return [
    `## Lazarus Deal Rescue — ${client}`,
    "",
    `**Deal Status:** ${status}`,
    dri != null ? `**Deal Risk Index:** ${dri}` : null,
    "",
    `**Root Issue:** ${rootIssue}`,
    "",
    `**Core Blocker:** ${blocker}`,
    "",
    `**Invisible Veto Holder:** ${veto}`,
    "",
    `**Next Action Date:** ${nextDate}`,
    "",
    "**30-Day Priority:**",
    priority,
    "",
    `*Generated by Lazarus · ${new Date().toISOString().slice(0, 10)}*`,
  ]
    .filter((line) => line !== null)
    .join("\n");
}
